import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { AppStateProvider } from "@/components/AppState";
import { CommandPalette } from "@/components/CommandPalette";
import { MobileGate } from "@/components/MobileGate";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Carl Ras Forhandler Partnerskab",
  description:
    "Platformen, kufferten og kommunikationsmotoren — én motor, alle temaer, hele Gruppen.",
  // /icon and /apple-icon are auto-generated by src/app/icon.tsx and
  // src/app/apple-icon.tsx (Next.js metadata routes). The existing
  // favicon-32 stays as a small-size fallback for browser tabs.
  icons: {
    icon: [
      { url: "/favicon-32.png", sizes: "32x32" },
      { url: "/icon", sizes: "512x512", type: "image/png" },
    ],
    apple: { url: "/apple-icon", sizes: "180x180", type: "image/png" },
  },
  // /manifest.webmanifest is auto-generated by src/app/manifest.ts —
  // makes the site installable as a PWA on iOS, Android, and desktop.
  manifest: "/manifest.webmanifest",
  // iOS-specific so the standalone-launched app drops the Safari chrome
  // and shows our theme color in the status bar area.
  appleWebApp: {
    capable: true,
    title: "Carl Ras Partner",
    statusBarStyle: "default",
  },
};

/** Viewport config — explicit so iOS Safari respects safe-area insets
 *  and the layout responds correctly on Pro Max devices. */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#1158A3",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="da" className={`${inter.variable} h-full antialiased`}>
      <head>
        {/* Carl Ras brand font — Neo Sans via Adobe Typekit. Inter loads via
            next/font as a fast-paint fallback and covers the medium weights
            (500/600) that this Typekit doesn't ship. */}
        <link rel="stylesheet" href="https://use.typekit.net/gqe3rsn.css" />
      </head>
      <body className="min-h-full">
        <AppStateProvider>
          <ThemeProvider>
            {children}
            <CommandPalette />
            {/* Mobile gate — shown only on <md viewports on routes that
                haven't been rebuilt mobile-first yet. Renders nothing on
                desktop or on the 4 mobile-ready hero routes. */}
            <MobileGate />
          </ThemeProvider>
        </AppStateProvider>
      </body>
    </html>
  );
}
