import type { MetadataRoute } from "next";

/* Web App Manifest — makes the demo installable as a PWA on mobile/desktop.
   Users can "Add to home screen" (iOS) or "Install app" (Chrome) and the
   site launches in its own window with a real app icon and splash screen.

   No service worker for now — pure manifest + icons. That's enough for the
   install flow on iOS Safari and Chromium, just without offline support. */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Carl Ras Forhandler Partnerskab",
    short_name: "Carl Ras Partner",
    description:
      "Platformen, kufferten og kommunikationsmotoren — Carl Ras Forhandler Partnerskab.",
    start_url: "/partner",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#FFFFFF",
    theme_color: "#1158A3",
    lang: "da-DK",
    icons: [
      // Auto-generated by /app/icon.tsx and /app/apple-icon.tsx — Next.js
      // hosts them at /icon and /apple-icon. They're picked up by the
      // manifest below.
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "maskable" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png" },
    ],
    categories: ["business", "productivity"],
  };
}
